### ISSUE TITLE
ExtraData: unpack(b) received extra data.

### ISSUE THREAD

**Issue by dmitry-saritasa** [msgpack/msgpack-python#223]
Getting the following msgpack encoded value from Kafka

```
In [32]: message.value
Out[32]: b'\xdc\x00\x15\xd9$00000000-0000-0000-0000-000000000000\xc0\xd9$00000000-0000-0000-0000-000000000000\xc0\xc0\xd9$00000000-0000-0000-0000-000000000000\xa0\xd2X\xc8d:\xc3\xd9$3c4d1a52-536c-421a-b258-346b06097fda\xd9$1ceb5f07-b62a-4d3b-811a-d2adfce45496\xae192.168.14.177\xc2\xa9OSXEditor\xb0Mac OS X 10.12.3\xd9$c5966702-2936-4028-b911-c417cea9744f\x00\xd9$19fba27e-abf9-4be1-b8c9-eb583f3b3f61\xcd\x13\xd0\xd9$87bafec1-5368-4b5c-8368-7309a3e39a80\xca\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

In [33]: msgpack.unpackb(message.value)
---------------------------------------------------------------------------
ExtraData                                 Traceback (most recent call last)
<ipython-input-33-31c954e1d841> in <module>()
----> 1 msgpack.unpackb(message.value)

msgpack/_unpacker.pyx in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)()

ExtraData: unpack(b) received extra data.

```

I parsed the data with https://github.com/tagomoris/msgpack-inspect and it seems **array16** is not being handled by msgpack-python?

```
---
- format: "array16"
  header: "0xdc"
  length: 21
  children:
    - format: "str8"
      header: "0xd9"
      length: 36
      data: "0x30303030303030302d303030302d303030302d303030302d303030303030303030303030"
      value: "00000000-0000-0000-0000-000000000000"
    - format: "nil"
      header: "0xc0"
      data: "0xc0"
      value: null
    - format: "str8"
      header: "0xd9"
      length: 36
      data: "0x30303030303030302d303030302d303030302d303030302d303030303030303030303030"
      value: "00000000-0000-0000-0000-000000000000"
    - format: "nil"
      header: "0xc0"
      data: "0xc0"
      value: null
    - format: "nil"
      header: "0xc0"
      data: "0xc0"
      value: null
    - format: "str8"
      header: "0xd9"
      length: 36
      data: "0x30303030303030302d303030302d303030302d303030302d303030303030303030303030"
      value: "00000000-0000-0000-0000-000000000000"
    - format: "fixstr"
      header: "0xa0"
      length: 0
      data: "0x"
      value: ""
    - format: "int32"
      header: "0xd2"
      data: "0x58c8643a"
      value: 1489527866
    - format: "true"
      header: "0xc3"
      data: "0xc3"
      value: true
    - format: "str8"
      header: "0xd9"
      length: 36
      data: "0x33633464316135322d353336632d343231612d623235382d333436623036303937666461"
      value: "3c4d1a52-536c-421a-b258-346b06097fda"
    - format: "str8"
      header: "0xd9"
      length: 36
      data: "0x31636562356630372d623632612d346433622d383131612d643261646663653435343936"
      value: "1ceb5f07-b62a-4d3b-811a-d2adfce45496"
    - format: "fixstr"
      header: "0xae"
      length: 14
      data: "0x3139322e3136382e31342e313737"
      value: "192.168.14.177"
    - format: "false"
      header: "0xc2"
      data: "0xc2"
      value: false
    - format: "fixstr"
      header: "0xa9"
      length: 9
      data: "0x4f5358456469746f72"
      value: "OSXEditor"
    - format: "fixstr"
      header: "0xb0"
      length: 16
      data: "0x4d6163204f5320582031302e31322e33"
      value: "Mac OS X 10.12.3"
    - format: "str8"
      header: "0xd9"
      length: 36
      data: "0x63353936363730322d323933362d343032382d623931312d633431376365613937343466"
      value: "c5966702-2936-4028-b911-c417cea9744f"
    - format: "fixint"
      header: "0x00"
      data: "0x00"
      value: 0
    - format: "str8"
      header: "0xd9"
      length: 36
      data: "0x31396662613237652d616266392d346265312d623863392d656235383366336233663631"
      value: "19fba27e-abf9-4be1-b8c9-eb583f3b3f61"
    - format: "uint16"
      header: "0xcd"
      data: "0x13d0"
      value: 5072
    - format: "str8"
      header: "0xd9"
      length: 36
      data: "0x38376261666563312d353336382d346235632d383336382d373330396133653339613830"
      value: "87bafec1-5368-4b5c-8368-7309a3e39a80"
    - format: "float32"
      header: "0xca"
      data: "0x00000000"
      value: 0.0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
- format: "fixint"
  header: "0x00"
  data: "0x00"
  value: 0
```

**any ideas?**
